import { toPascalCase } from "../sdk-common/mapper";
import type { TypeMapper } from "../sdk-common/type-utils";
import { resolveFieldType } from "../sdk-common/type-utils";
import type { BuildOptions, MappedEvent, ResolvedField, SdkBuilder } from "../sdk-common/types";

export type { BuildOptions };

// --- Swift type mapper ---

const SWIFT_BASE_TYPES: Record<string, string> = {
  string: "String",
  integer: "Int",
  number: "Double",
  boolean: "Bool",
  unknown: "Any",
};

export const swiftTypeMapper: TypeMapper = {
  baseType(type: string): string {
    return SWIFT_BASE_TYPES[type] ?? "Any";
  },
  enumLiteral(value: string | number | boolean): string {
    if (typeof value === "string") return `"${value}"`;
    return String(value);
  },
  enumUnion(_values: (string | number | boolean)[]): string {
    // In Swift, enums are named types — this returns a placeholder.
    // Actual enum rendering is handled separately.
    return "String";
  },
  arrayOf(innerType: string): string {
    return `[${innerType}]`;
  },
  optional(type: string): string {
    return `${type}?`;
  },
};

// --- Helpers ---

/** Convert a snake_case field name to camelCase for Swift properties */
function toCamelCase(str: string): string {
  return str.replace(/[_-](\w)/g, (_, c) => c.toUpperCase());
}

/** Generate a Swift enum name from a field name, e.g. "auth_method" → "AuthMethod" */
function enumName(fieldName: string): string {
  return toPascalCase(fieldName);
}

/** Swift reserved keywords that need backtick escaping in enum cases */
const SWIFT_KEYWORDS = new Set([
  "associatedtype",
  "class",
  "deinit",
  "enum",
  "extension",
  "fileprivate",
  "func",
  "import",
  "init",
  "inout",
  "internal",
  "let",
  "open",
  "operator",
  "private",
  "protocol",
  "public",
  "rethrows",
  "static",
  "struct",
  "subscript",
  "typealias",
  "var",
  "break",
  "case",
  "continue",
  "default",
  "defer",
  "do",
  "else",
  "fallthrough",
  "for",
  "guard",
  "if",
  "in",
  "repeat",
  "return",
  "switch",
  "where",
  "while",
  "as",
  "catch",
  "false",
  "is",
  "nil",
  "self",
  "Self",
  "super",
  "throw",
  "throws",
  "true",
  "try",
]);

/** Convert an enum value to a valid Swift case identifier */
function toEnumCase(value: string | number | boolean): string {
  let str = String(value);
  // Convert snake_case or kebab-case to camelCase
  str = str.replace(/[_-](\w)/g, (_, c) => c.toUpperCase());
  // Prefix with underscore if starts with a digit
  if (/^\d/.test(str)) {
    str = `_${str}`;
  }
  // Backtick-escape Swift reserved keywords
  if (SWIFT_KEYWORDS.has(str)) {
    str = `\`${str}\``;
  }
  return str;
}

/**
 * Determine the Swift type string for a field.
 * For enum fields, returns the generated enum name.
 * For arrays of enums, returns [EnumName].
 */
export function fieldToSwiftType(field: ResolvedField): string {
  // Array with enum items → [EnumName]
  if (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0) {
    const allBooleans = field.arrayItemEnum.every((v) => typeof v === "boolean");
    if (allBooleans && field.arrayItemEnum.includes(true) && field.arrayItemEnum.includes(false)) {
      return "[Bool]";
    }
    return `[${enumName(field.name)}]`;
  }

  // Array with plain item type
  if (field.isArray && field.arrayItemType) {
    return resolveFieldType(field, swiftTypeMapper);
  }

  // Array with no items info
  if (field.isArray) {
    return "[Any]";
  }

  // Non-array with enum values → named enum type
  if (field.enumValues && field.enumValues.length > 0) {
    const allBooleans = field.enumValues.every((v) => typeof v === "boolean");
    if (allBooleans && field.enumValues.includes(true) && field.enumValues.includes(false)) {
      return "Bool";
    }
    return enumName(field.name);
  }

  // Scalar
  return resolveFieldType(field, swiftTypeMapper);
}

// --- Rendering functions ---

function renderHeader(eventCount: number, options: BuildOptions): string {
  const lines = [
    "//",
    "// Auto-generated by OpenTrackPlan CLI",
    "// DO NOT EDIT MANUALLY",
    "//",
    `// Tracking plan: ${options.planTitle} v${options.planVersion}`,
    `// Generated at: ${options.generatedAt}`,
    `// Target: ${options.targetName}`,
    `// Events: ${eventCount}`,
    "//",
    "",
    "import Foundation",
  ];
  return lines.join("\n");
}

/** Render a Swift enum for a field with enum values */
export function renderEnum(fieldName: string, values: (string | number | boolean)[]): string {
  const name = enumName(fieldName);
  const lines: string[] = [];
  lines.push(`enum ${name}: String, CaseIterable, Codable {`);
  for (const v of values) {
    const caseName = toEnumCase(v);
    const rawValue = String(v);
    // Only add explicit raw value if it differs from the case name
    if (caseName !== rawValue) {
      lines.push(`    case ${caseName} = "${rawValue}"`);
    } else {
      lines.push(`    case ${caseName}`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

/** Check if a field name differs from its camelCase form (needs CodingKeys) */
function needsCodingKey(name: string): boolean {
  return name !== toCamelCase(name);
}

/** Render a struct for an event's parameters */
export function renderStruct(event: MappedEvent): string {
  const lines: string[] = [];
  lines.push(`struct ${event.interfaceName}: Codable {`);

  for (const field of event.params) {
    if (field.piiKind) {
      lines.push(`    /// PII: ${field.piiKind}`);
    }
    const swiftType = fieldToSwiftType(field);
    const propName = toCamelCase(field.name);
    if (field.required) {
      lines.push(`    let ${propName}: ${swiftType}`);
    } else {
      lines.push(`    var ${propName}: ${swiftType}?`);
    }
  }

  // CodingKeys — only if any field name differs from its camelCase form
  const fieldsNeedingKeys = event.params.filter((f) => needsCodingKey(f.name));
  if (fieldsNeedingKeys.length > 0) {
    lines.push("");
    lines.push("    enum CodingKeys: String, CodingKey {");
    for (const field of event.params) {
      const propName = toCamelCase(field.name);
      if (needsCodingKey(field.name)) {
        lines.push(`        case ${propName} = "${field.name}"`);
      } else {
        lines.push(`        case ${propName}`);
      }
    }
    lines.push("    }");
  }

  lines.push("}");
  return lines.join("\n");
}

function renderConstantValue(value: string | number | boolean): string {
  if (typeof value === "string") return `"${value.replace(/"/g, '\\"')}"`;
  if (typeof value === "boolean") return value ? "true" : "false";
  return String(value);
}

function renderBuildPayload(event: MappedEvent, indent: string): string {
  const lines: string[] = [];
  const hasParams = event.params.length > 0;

  if (hasParams) {
    lines.push(
      `${indent}static func buildPayload(_ params: ${event.interfaceName}) -> [String: Any] {`,
    );
  } else {
    lines.push(`${indent}static func buildPayload() -> [String: Any] {`);
  }

  lines.push(`${indent}    var payload: [String: Any] = [`);

  // Constants
  for (const [k, v] of Object.entries(event.constants)) {
    lines.push(`${indent}        "${k}": ${renderConstantValue(v)},`);
  }

  lines.push(`${indent}    ]`);

  // Params
  if (hasParams) {
    for (const field of event.params) {
      const propName = toCamelCase(field.name);
      const hasEnum =
        (field.enumValues && field.enumValues.length > 0) ||
        (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0);

      if (field.required) {
        if (hasEnum && !field.isArray) {
          lines.push(`${indent}    payload["${field.name}"] = params.${propName}.rawValue`);
        } else if (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0) {
          lines.push(
            `${indent}    payload["${field.name}"] = params.${propName}.map { $0.rawValue }`,
          );
        } else {
          lines.push(`${indent}    payload["${field.name}"] = params.${propName}`);
        }
      } else {
        if (hasEnum && !field.isArray) {
          lines.push(
            `${indent}    if let ${propName} = params.${propName} { payload["${field.name}"] = ${propName}.rawValue }`,
          );
        } else if (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0) {
          lines.push(
            `${indent}    if let ${propName} = params.${propName} { payload["${field.name}"] = ${propName}.map { $0.rawValue } }`,
          );
        } else {
          lines.push(
            `${indent}    if let ${propName} = params.${propName} { payload["${field.name}"] = ${propName} }`,
          );
        }
      }
    }
  }

  lines.push(`${indent}    return payload`);
  lines.push(`${indent}}`);
  return lines.join("\n");
}

function renderEventsRegistry(events: MappedEvent[]): string {
  // Group by area
  const groups = new Map<string, MappedEvent[]>();
  for (const event of events) {
    const list = groups.get(event.area) ?? [];
    list.push(event);
    groups.set(event.area, list);
  }

  const sortedAreas = [...groups.keys()].sort();
  if (sortedAreas.length === 0) {
    return "enum Events {}";
  }

  const lines: string[] = [];
  lines.push("enum Events {");

  for (const area of sortedAreas) {
    const areaEvents = groups.get(area)!;
    areaEvents.sort((a, b) => a.eventName.localeCompare(b.eventName));

    lines.push(`    enum ${toPascalCase(area)} {`);

    for (const event of areaEvents) {
      lines.push(`        static let ${event.eventName} = "${event.key}"`);
    }

    // buildPayload for each event
    for (const event of areaEvents) {
      lines.push("");
      lines.push(renderBuildPayload(event, "        "));
    }

    lines.push("    }");
  }

  lines.push("}");
  return lines.join("\n");
}

// --- Main build function ---

export function buildSwift(events: MappedEvent[], options: BuildOptions): string {
  const sections: string[] = [];

  // 1. Header
  sections.push(renderHeader(events.length, options));

  // 2. Enums for fields with enum values
  const renderedEnums = new Set<string>();
  for (const event of events) {
    for (const field of event.params) {
      const key = enumName(field.name);
      if (field.enumValues && field.enumValues.length > 0 && !renderedEnums.has(key)) {
        sections.push(renderEnum(field.name, field.enumValues));
        renderedEnums.add(key);
      }
      if (
        field.isArray &&
        field.arrayItemEnum &&
        field.arrayItemEnum.length > 0 &&
        !renderedEnums.has(key)
      ) {
        sections.push(renderEnum(field.name, field.arrayItemEnum));
        renderedEnums.add(key);
      }
    }
  }

  // 3. Structs for events with params
  for (const event of events) {
    if (event.params.length > 0) {
      sections.push(renderStruct(event));
    }
  }

  // 4. Events registry
  sections.push(renderEventsRegistry(events));

  return `${sections.join("\n\n")}\n`;
}

// --- SdkBuilder implementation ---

export const swiftBuilder: SdkBuilder = {
  extension: "swift",
  language: "Swift",
  build: buildSwift,
};
