import { describe, expect, it } from "vitest";
import type { OpenTPConfig, ResolvedEvent } from "../../types";
import type { GeneratorContext, GeneratorOptions } from "../types";
import { swiftSdkGenerator } from "./index";

// -- Shared Fixtures --

const baseConfig: OpenTPConfig = {
  opentp: "2026-01",
  info: { title: "My App", version: "2.0.0" },
  spec: {
    paths: { events: { root: "/events", template: "{area}/{event}.yaml" } },
    events: {
      taxonomy: {},
      payload: {
        targets: { all: ["web", "ios", "android"], mobile: ["ios", "android"] },
        schema: {
          event_name: { type: "string", required: true },
          event_category: { type: "string", required: true },
        },
      },
    },
  },
};

const emptyDict = new Map<string, (string | number | boolean)[]>();

function makeEvent(overrides: Partial<ResolvedEvent>): ResolvedEvent {
  return {
    filePath: "/events/test/event.yaml",
    relativePath: "test/event.yaml",
    key: "test::event",
    expectedKey: null,
    taxonomy: { area: "test", event: "event" },
    ignore: [],
    payload: { schema: {} },
    ...overrides,
  };
}

function makeContext(
  events: ResolvedEvent[],
  options: GeneratorOptions = {},
  dictionaries = emptyDict,
): GeneratorContext {
  return { config: baseConfig, events, dictionaries, options };
}

// -- Tests --

describe("swift-sdk generator (integration)", () => {
  it("generates valid Swift for a minimal tracking plan", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "auth::login_button_click",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "login_button_click" },
              event_category: { value: "auth" },
              auth_method: {
                type: "string",
                enum: ["email", "google"],
                required: true,
              },
            },
          },
        }),
      ],
      { target: "ios" },
    );

    const result = swiftSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("Auto-generated by OpenTrackPlan CLI");
    expect(output).toContain("My App v2.0.0");
    expect(output).toContain("Target: ios");
    expect(output).toContain("Events: 1");
    expect(output).toContain("import Foundation");
    expect(output).toContain("enum AuthMethod: String, CaseIterable, Codable");
    expect(output).toContain("struct AuthLoginButtonClickParams: Codable");
    expect(output).toContain("enum Events {");
    expect(output).toContain("enum Auth {");
    expect(output).toContain('static let loginButtonClick = "auth::login_button_click"');
    expect(output).toContain("buildPayload");
  });

  it("generates valid Swift for events with dictionaries", () => {
    const dicts = new Map<string, (string | number | boolean)[]>([
      ["auth_methods", ["email", "google", "sso"]],
    ]);

    const context = makeContext(
      [
        makeEvent({
          key: "auth::signup",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "signup" },
              event_category: { value: "auth" },
              method: { type: "string", dict: "auth_methods", required: true },
            },
          },
        }),
      ],
      { target: "ios" },
      dicts,
    );

    const result = swiftSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("enum Method: String, CaseIterable, Codable");
    expect(output).toContain("case email");
    expect(output).toContain("case google");
    expect(output).toContain("case sso");
  });

  it("filters events by target (ios)", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "onboarding::step_complete",
          payload: {
            mobile: {
              schema: {
                event_name: { value: "step_complete" },
                event_category: { value: "onboarding" },
                step: { type: "number", required: true },
              },
            },
          },
        }),
      ],
      { target: "web" },
    );

    const result = swiftSdkGenerator.generate(context);
    const output = result.stdout!;
    expect(output).not.toContain("stepComplete");
    expect(output).toContain("Events: 0");
  });

  it("handles empty event list gracefully", () => {
    const context = makeContext([], { target: "ios" });
    const result = swiftSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("Events: 0");
    expect(output).toContain("enum Events {}");
  });

  it("resolves dictionary enum values into Swift enums", () => {
    const dicts = new Map<string, (string | number | boolean)[]>([
      ["platforms", ["ios", "android", "web"]],
    ]);

    const context = makeContext(
      [
        makeEvent({
          key: "analytics::track",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "track" },
              event_category: { value: "analytics" },
              platform: { type: "string", dict: "platforms", required: true },
            },
          },
        }),
      ],
      { target: "ios" },
      dicts,
    );

    const result = swiftSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("enum Platform: String, CaseIterable, Codable");
    expect(output).toContain("case ios");
    expect(output).toContain("case android");
    expect(output).toContain("case web");
    expect(output).toContain("params.platform.rawValue");
  });

  it("handles digit-leading enum values with underscore prefix", () => {
    const dicts = new Map<string, (string | number | boolean)[]>([
      ["company_sizes", ["1", "2_10", "11_50", "1000_plus"]],
    ]);

    const context = makeContext(
      [
        makeEvent({
          key: "onboarding::company_info",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "company_info" },
              event_category: { value: "onboarding" },
              company_size: { type: "string", dict: "company_sizes", required: true },
            },
          },
        }),
      ],
      { target: "ios" },
      dicts,
    );

    const result = swiftSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("enum CompanySize: String, CaseIterable, Codable");
    expect(output).toContain('case _1 = "1"');
    expect(output).toContain('case _210 = "2_10"');
    expect(output).toContain('case _1150 = "11_50"');
    expect(output).toContain('case _1000Plus = "1000_plus"');
  });

  it("backtick-escapes Swift reserved keywords in enum cases", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "projects::created",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "created" },
              event_category: { value: "projects" },
              visibility: {
                type: "string",
                enum: ["private", "public", "team"],
                required: true,
              },
            },
          },
        }),
      ],
      { target: "ios" },
    );

    const result = swiftSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("case `private`");
    expect(output).toContain("case `public`");
    expect(output).toContain("case team");
  });
});
