import { toPascalCase } from "../sdk-common/mapper";
import type { TypeMapper } from "../sdk-common/type-utils";
import { resolveFieldType } from "../sdk-common/type-utils";
import type { BuildOptions, MappedEvent, ResolvedField, SdkBuilder } from "../sdk-common/types";

export type { BuildOptions };

// --- Kotlin type mapper ---

const KOTLIN_BASE_TYPES: Record<string, string> = {
  string: "String",
  integer: "Int",
  number: "Double",
  boolean: "Boolean",
  unknown: "Any",
};

export const kotlinTypeMapper: TypeMapper = {
  baseType(type: string): string {
    return KOTLIN_BASE_TYPES[type] ?? "Any";
  },
  enumLiteral(value: string | number | boolean): string {
    if (typeof value === "string") return `"${value}"`;
    return String(value);
  },
  enumUnion(_values: (string | number | boolean)[]): string {
    return "String";
  },
  arrayOf(innerType: string): string {
    return `List<${innerType}>`;
  },
  optional(type: string): string {
    return `${type}?`;
  },
};

// --- Helpers ---

function toCamelCase(str: string): string {
  return str.replace(/[_-](\w)/g, (_, c) => c.toUpperCase());
}

function enumClassName(fieldName: string): string {
  return toPascalCase(fieldName);
}

/** Convert a value to UPPER_CASE for Kotlin enum entries */
function toUpperCase(value: string | number | boolean): string {
  let str = String(value).toUpperCase().replace(/[- ]/g, "_");
  // Prefix with underscore if starts with a digit
  if (/^\d/.test(str)) {
    str = `_${str}`;
  }
  return str;
}

/**
 * Determine the Kotlin type string for a field.
 * For enum fields, returns the generated enum class name.
 */
export function fieldToKotlinType(field: ResolvedField): string {
  // Array with enum items → List<EnumName>
  if (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0) {
    const allBooleans = field.arrayItemEnum.every((v) => typeof v === "boolean");
    if (allBooleans && field.arrayItemEnum.includes(true) && field.arrayItemEnum.includes(false)) {
      return "List<Boolean>";
    }
    return `List<${enumClassName(field.name)}>`;
  }

  // Array with plain item type
  if (field.isArray && field.arrayItemType) {
    return resolveFieldType(field, kotlinTypeMapper);
  }

  // Array with no items info
  if (field.isArray) {
    return "List<Any>";
  }

  // Non-array with enum values → named enum class
  if (field.enumValues && field.enumValues.length > 0) {
    const allBooleans = field.enumValues.every((v) => typeof v === "boolean");
    if (allBooleans && field.enumValues.includes(true) && field.enumValues.includes(false)) {
      return "Boolean";
    }
    return enumClassName(field.name);
  }

  // Scalar
  return resolveFieldType(field, kotlinTypeMapper);
}

// --- Rendering functions ---

function renderHeader(eventCount: number, options: BuildOptions, standalone: boolean): string {
  const lines = [
    "/**",
    " * Auto-generated by OpenTrackPlan CLI",
    " * DO NOT EDIT MANUALLY",
    " *",
    ` * Tracking plan: ${options.planTitle} v${options.planVersion}`,
    ` * Generated at: ${options.generatedAt}`,
    ` * Target: ${options.targetName}`,
    ` * Events: ${eventCount}`,
  ];

  if (!standalone) {
    lines.push(" *");
    lines.push(" * Requires kotlinx-serialization-json on classpath");
    lines.push(" * and the Kotlin serialization compiler plugin.");
  }

  lines.push(" */");

  if (!standalone) {
    lines.push("");
    lines.push("import kotlinx.serialization.*");
  }

  return lines.join("\n");
}

/** Render a Kotlin enum class for a field with enum values */
export function renderEnumClass(
  fieldName: string,
  values: (string | number | boolean)[],
  standalone: boolean,
): string {
  const name = enumClassName(fieldName);
  const lines: string[] = [];

  if (!standalone) {
    lines.push("@Serializable");
  }

  lines.push(`enum class ${name}(val value: String) {`);

  for (let i = 0; i < values.length; i++) {
    const v = values[i];
    const entryName = toUpperCase(v);
    const rawValue = String(v);
    const separator = i < values.length - 1 ? "," : ";";

    if (!standalone) {
      lines.push(`    @SerialName("${rawValue}")`);
    }
    lines.push(`    ${entryName}("${rawValue}")${separator}`);
  }

  lines.push("}");
  return lines.join("\n");
}

/** Render a data class for an event's parameters */
export function renderDataClass(event: MappedEvent, standalone: boolean): string {
  const lines: string[] = [];

  if (!standalone) {
    lines.push("@Serializable");
  }

  lines.push(`data class ${event.interfaceName}(`);

  for (let i = 0; i < event.params.length; i++) {
    const field = event.params[i];
    const propName = toCamelCase(field.name);
    const kotlinType = fieldToKotlinType(field);
    const trailing = i < event.params.length - 1 ? "," : "";

    if (field.piiKind) {
      lines.push(`    /** PII: ${field.piiKind} */`);
    }

    if (!standalone && field.name !== propName) {
      lines.push(`    @SerialName("${field.name}")`);
    }

    if (field.required) {
      lines.push(`    val ${propName}: ${kotlinType}${trailing}`);
    } else {
      lines.push(`    val ${propName}: ${kotlinType}? = null${trailing}`);
    }
  }

  lines.push(")");
  return lines.join("\n");
}

function renderConstantValue(value: string | number | boolean): string {
  if (typeof value === "string") return `"${value.replace(/"/g, '\\"')}"`;
  if (typeof value === "boolean") return value ? "true" : "false";
  return String(value);
}

function renderBuildPayload(event: MappedEvent, indent: string): string {
  const lines: string[] = [];
  const hasParams = event.params.length > 0;

  if (hasParams) {
    lines.push(`${indent}fun buildPayload(params: ${event.interfaceName}): Map<String, Any> {`);
  } else {
    lines.push(`${indent}fun buildPayload(): Map<String, Any> {`);
  }

  lines.push(`${indent}    val payload = mutableMapOf<String, Any>(`);

  for (const [k, v] of Object.entries(event.constants)) {
    lines.push(`${indent}        "${k}" to ${renderConstantValue(v)},`);
  }

  lines.push(`${indent}    )`);

  if (hasParams) {
    for (const field of event.params) {
      const propName = toCamelCase(field.name);
      const hasEnum =
        (field.enumValues && field.enumValues.length > 0) ||
        (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0);

      if (field.required) {
        if (hasEnum && !field.isArray) {
          lines.push(`${indent}    payload["${field.name}"] = params.${propName}.value`);
        } else if (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0) {
          lines.push(`${indent}    payload["${field.name}"] = params.${propName}.map { it.value }`);
        } else {
          lines.push(`${indent}    payload["${field.name}"] = params.${propName}`);
        }
      } else {
        if (hasEnum && !field.isArray) {
          lines.push(
            `${indent}    params.${propName}?.let { payload["${field.name}"] = it.value }`,
          );
        } else if (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0) {
          lines.push(
            `${indent}    params.${propName}?.let { payload["${field.name}"] = it.map { e -> e.value } }`,
          );
        } else {
          lines.push(`${indent}    params.${propName}?.let { payload["${field.name}"] = it }`);
        }
      }
    }
  }

  lines.push(`${indent}    return payload`);
  lines.push(`${indent}}`);
  return lines.join("\n");
}

function renderEventsRegistry(events: MappedEvent[]): string {
  const groups = new Map<string, MappedEvent[]>();
  for (const event of events) {
    const list = groups.get(event.area) ?? [];
    list.push(event);
    groups.set(event.area, list);
  }

  const sortedAreas = [...groups.keys()].sort();
  if (sortedAreas.length === 0) {
    return "object Events";
  }

  const lines: string[] = [];
  lines.push("object Events {");

  for (const area of sortedAreas) {
    const areaEvents = groups.get(area)!;
    areaEvents.sort((a, b) => a.eventName.localeCompare(b.eventName));

    lines.push(`    object ${toPascalCase(area)} {`);

    for (const event of areaEvents) {
      lines.push(`        val ${event.eventName} = "${event.key}"`);
    }

    for (const event of areaEvents) {
      lines.push("");
      lines.push(renderBuildPayload(event, "        "));
    }

    lines.push("    }");
  }

  lines.push("}");
  return lines.join("\n");
}

// --- Main build function ---

export function buildKotlin(events: MappedEvent[], options: BuildOptions): string {
  const sections: string[] = [];
  const standalone = options.standalone ?? false;

  // 1. Header
  sections.push(renderHeader(events.length, options, standalone));

  // 2. Enum classes for fields with enum values
  const renderedEnums = new Set<string>();
  for (const event of events) {
    for (const field of event.params) {
      const key = enumClassName(field.name);
      if (field.enumValues && field.enumValues.length > 0 && !renderedEnums.has(key)) {
        sections.push(renderEnumClass(field.name, field.enumValues, standalone));
        renderedEnums.add(key);
      }
      if (
        field.isArray &&
        field.arrayItemEnum &&
        field.arrayItemEnum.length > 0 &&
        !renderedEnums.has(key)
      ) {
        sections.push(renderEnumClass(field.name, field.arrayItemEnum, standalone));
        renderedEnums.add(key);
      }
    }
  }

  // 3. Data classes for events with params
  for (const event of events) {
    if (event.params.length > 0) {
      sections.push(renderDataClass(event, standalone));
    }
  }

  // 4. Events registry
  sections.push(renderEventsRegistry(events));

  return `${sections.join("\n\n")}\n`;
}

// --- SdkBuilder implementation ---

export const kotlinBuilder: SdkBuilder = {
  extension: "kt",
  language: "Kotlin",
  build: buildKotlin,
};
