import { describe, expect, it } from "vitest";
import type { OpenTPConfig, ResolvedEvent } from "../../types";
import type { GeneratorContext, GeneratorOptions } from "../types";
import { kotlinSdkGenerator } from "./index";

// -- Shared Fixtures --

const baseConfig: OpenTPConfig = {
  opentp: "2026-01",
  info: { title: "My App", version: "2.0.0" },
  spec: {
    paths: { events: { root: "/events", template: "{area}/{event}.yaml" } },
    events: {
      taxonomy: {},
      payload: {
        targets: { all: ["web", "ios", "android"], mobile: ["ios", "android"] },
        schema: {
          event_name: { type: "string", required: true },
          event_category: { type: "string", required: true },
        },
      },
    },
  },
};

const emptyDict = new Map<string, (string | number | boolean)[]>();

function makeEvent(overrides: Partial<ResolvedEvent>): ResolvedEvent {
  return {
    filePath: "/events/test/event.yaml",
    relativePath: "test/event.yaml",
    key: "test::event",
    expectedKey: null,
    taxonomy: { area: "test", event: "event" },
    ignore: [],
    payload: { schema: {} },
    ...overrides,
  };
}

function makeContext(
  events: ResolvedEvent[],
  options: GeneratorOptions = {},
  dictionaries = emptyDict,
): GeneratorContext {
  return { config: baseConfig, events, dictionaries, options };
}

// -- Tests --

describe("kotlin-sdk generator (integration)", () => {
  it("generates valid Kotlin for a minimal tracking plan", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "auth::login_button_click",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "login_button_click" },
              event_category: { value: "auth" },
              auth_method: {
                type: "string",
                enum: ["email", "google"],
                required: true,
              },
            },
          },
        }),
      ],
      { target: "android", standalone: true },
    );

    const result = kotlinSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("Auto-generated by OpenTrackPlan CLI");
    expect(output).toContain("My App v2.0.0");
    expect(output).toContain("Target: android");
    expect(output).toContain("Events: 1");
    expect(output).toContain("enum class AuthMethod(val value: String)");
    expect(output).toContain("data class AuthLoginButtonClickParams(");
    expect(output).toContain("object Events {");
    expect(output).toContain("object Auth {");
    expect(output).toContain('val loginButtonClick = "auth::login_button_click"');
    expect(output).toContain("buildPayload");
  });

  it("generates valid Kotlin for events with dictionaries", () => {
    const dicts = new Map<string, (string | number | boolean)[]>([
      ["auth_methods", ["email", "google", "sso"]],
    ]);

    const context = makeContext(
      [
        makeEvent({
          key: "auth::signup",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "signup" },
              event_category: { value: "auth" },
              method: { type: "string", dict: "auth_methods", required: true },
            },
          },
        }),
      ],
      { target: "android", standalone: true },
      dicts,
    );

    const result = kotlinSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("enum class Method(val value: String)");
    expect(output).toContain('EMAIL("email")');
    expect(output).toContain('GOOGLE("google")');
    expect(output).toContain('SSO("sso")');
  });

  it("filters events by target (android)", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "onboarding::step_complete",
          payload: {
            mobile: {
              schema: {
                event_name: { value: "step_complete" },
                event_category: { value: "onboarding" },
                step: { type: "number", required: true },
              },
            },
          },
        }),
      ],
      { target: "web", standalone: true },
    );

    const result = kotlinSdkGenerator.generate(context);
    const output = result.stdout!;
    expect(output).not.toContain("stepComplete");
    expect(output).toContain("Events: 0");
  });

  it("handles empty event list gracefully", () => {
    const context = makeContext([], { target: "android", standalone: true });
    const result = kotlinSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("Events: 0");
    expect(output).toContain("object Events");
  });

  it("generates standalone vs non-standalone output", () => {
    const event = makeEvent({
      key: "auth::login",
      lifecycle: { status: "active" },
      payload: {
        schema: {
          event_name: { value: "login" },
          event_category: { value: "auth" },
          method: { type: "string", enum: ["email"], required: true },
        },
      },
    });

    // Standalone
    const standaloneCtx = makeContext([event], { target: "android", standalone: true });
    const standaloneOutput = (kotlinSdkGenerator.generate(standaloneCtx) as { stdout: string })
      .stdout;
    expect(standaloneOutput).not.toContain("kotlinx");
    expect(standaloneOutput).not.toContain("@Serializable");
    expect(standaloneOutput).not.toContain("@SerialName");

    // Non-standalone
    const sdkCtx = makeContext([event], { target: "android" });
    const sdkOutput = (kotlinSdkGenerator.generate(sdkCtx) as { stdout: string }).stdout;
    expect(sdkOutput).toContain("import kotlinx.serialization.*");
    expect(sdkOutput).toContain("@Serializable");
    expect(sdkOutput).toContain("@SerialName");
  });

  it("handles digit-leading enum values with underscore prefix", () => {
    const dicts = new Map<string, (string | number | boolean)[]>([
      ["company_sizes", ["1", "2_10", "11_50", "1000_plus"]],
    ]);

    const context = makeContext(
      [
        makeEvent({
          key: "onboarding::company_info",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "company_info" },
              event_category: { value: "onboarding" },
              company_size: { type: "string", dict: "company_sizes", required: true },
            },
          },
        }),
      ],
      { target: "android", standalone: true },
      dicts,
    );

    const result = kotlinSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("enum class CompanySize(val value: String)");
    expect(output).toContain('_1("1")');
    expect(output).toContain('_2_10("2_10")');
    expect(output).toContain('_11_50("11_50")');
    expect(output).toContain('_1000_PLUS("1000_plus")');
  });
});
