import { toPascalCase } from "../sdk-common/mapper";
import type { BuildOptions, MappedEvent, ResolvedField } from "../sdk-common/types";

export type { BuildOptions };

// Helper code for standalone mode (no @opentp/sdk dependency)
const STANDALONE_HELPER_CODE = `export interface TrackingEvent<TParams = void> {
  key: string;
  constants: Record<string, string | number | boolean>;
  buildPayload: TParams extends void
    ? () => Record<string, unknown>
    : (params: TParams) => Record<string, unknown>;
}

function defineEvent<TParams = void>(
  key: string,
  constants: Record<string, string | number | boolean>,
): TrackingEvent<TParams> {
  return {
    key,
    constants,
    buildPayload: ((params?: TParams) => ({
      ...constants,
      ...(params ?? {}),
    })) as TrackingEvent<TParams>['buildPayload'],
  };
}`;

const TYPE_EXPORTS = `export type EventsMap = typeof events;
export type AreaName = keyof EventsMap;
export type EventName<A extends AreaName> = keyof EventsMap[A];`;

function enumName(fieldName: string): string {
  return toPascalCase(fieldName);
}

/** Convert enum value to UPPER_SNAKE_CASE key (same logic as Kotlin builder) */
function toUpperCase(value: string | number | boolean): string {
  let str = String(value).toUpperCase().replace(/[- ]/g, "_");
  if (/^\d/.test(str)) str = `_${str}`;
  return str;
}

function mapBaseType(type: string): string {
  if (type === "integer") return "number";
  if (type === "string" || type === "number" || type === "boolean") return type;
  return "unknown";
}

export function renderEnumConst(fieldName: string, values: (string | number | boolean)[]): string {
  const name = enumName(fieldName);
  const entries = values.map((v) => {
    const key = toUpperCase(v);
    const val = typeof v === "string" ? `'${v}'` : String(v);
    return `  ${key}: ${val},`;
  });
  return [
    `export const ${name} = {`,
    ...entries,
    `} as const;`,
    `export type ${name} = typeof ${name}[keyof typeof ${name}];`,
  ].join("\n");
}

export function fieldToTsType(field: ResolvedField): string {
  // Array with enum items: EnumName[]
  if (field.isArray && field.arrayItemEnum && field.arrayItemEnum.length > 0) {
    const allBooleans = field.arrayItemEnum.every((v) => typeof v === "boolean");
    if (allBooleans && field.arrayItemEnum.includes(true) && field.arrayItemEnum.includes(false)) {
      return "boolean[]";
    }
    return `${enumName(field.name)}[]`;
  }

  // Array with plain item type: string[]
  if (field.isArray && field.arrayItemType) {
    return `${mapBaseType(field.arrayItemType)}[]`;
  }

  // Array with no items info
  if (field.isArray) {
    return "unknown[]";
  }

  // Non-array with enum values: EnumName
  if (field.enumValues && field.enumValues.length > 0) {
    const allBooleans = field.enumValues.every((v) => typeof v === "boolean");
    if (allBooleans && field.enumValues.includes(true) && field.enumValues.includes(false)) {
      return "boolean";
    }
    return enumName(field.name);
  }

  // Scalar base type
  return mapBaseType(field.baseType);
}

function renderHeader(eventCount: number, options: BuildOptions): string {
  const lines = [
    "/**",
    " * Auto-generated by OpenTrackPlan CLI",
    " * DO NOT EDIT MANUALLY",
    " *",
    ` * Tracking plan: ${options.planTitle} v${options.planVersion}`,
    ` * Generated at: ${options.generatedAt}`,
    ` * Target: ${options.targetName}`,
    ` * Events: ${eventCount}`,
  ];

  if (!options.standalone) {
    lines.push(" * Compatible with @opentp/sdk createTracker()");
  }

  lines.push(" */");

  // Add SDK import for non-standalone mode
  if (!options.standalone) {
    lines.push("");
    lines.push("import type { TrackingEvent } from '@opentp/sdk';");
  }

  return lines.join("\n");
}

function renderField(field: ResolvedField): string {
  const tag = field.required ? "@required" : "@optional";
  const parts = [tag];
  if (field.piiKind) {
    parts.push(`PII: ${field.piiKind}`);
  }
  const jsdoc = `  /** ${parts.join(" \u2014 ")} */`;
  const opt = field.required ? "" : "?";
  const line = `  ${field.name}${opt}: ${fieldToTsType(field)};`;
  return `${jsdoc}\n${line}`;
}

function renderInterface(event: MappedEvent): string {
  const fields = event.params.map(renderField).join("\n");
  return `export interface ${event.interfaceName} {\n${fields}\n}`;
}

function renderConstantValue(value: string | number | boolean): string {
  if (typeof value === "string") {
    return `'${value.replace(/'/g, "\\'")}'`;
  }
  return String(value);
}

function renderEventEntry(event: MappedEvent, indent: number, standalone: boolean): string {
  const pad = " ".repeat(indent);
  const innerPad = " ".repeat(indent + 2);

  // Standalone mode: use defineEvent helper
  if (standalone) {
    const typeParam = event.params.length > 0 ? `<${event.interfaceName}>` : "";
    const constEntries = Object.entries(event.constants);
    let constantsBlock: string;
    if (constEntries.length === 0) {
      constantsBlock = "{}";
    } else {
      const lines = constEntries.map(([k, v]) => `${innerPad}  ${k}: ${renderConstantValue(v)},`);
      constantsBlock = `{\n${lines.join("\n")}\n${innerPad}}`;
    }

    return [
      `${pad}${event.eventName}: defineEvent${typeParam}(`,
      `${innerPad}${renderConstantValue(event.key)},`,
      `${innerPad}${constantsBlock},`,
      `${pad}),`,
    ].join("\n");
  }

  // SDK mode: explicit object with satisfies
  const lines: string[] = [];
  const innerPad2 = " ".repeat(indent + 4);

  lines.push(`${pad}${event.eventName}: {`);
  lines.push(`${innerPad}key: ${renderConstantValue(event.key)},`);

  // Constants object
  const constEntries = Object.entries(event.constants);
  if (constEntries.length === 0) {
    lines.push(`${innerPad}constants: {},`);
  } else {
    lines.push(`${innerPad}constants: {`);
    for (const [k, v] of constEntries) {
      lines.push(`${innerPad2}${k}: ${renderConstantValue(v)},`);
    }
    lines.push(`${innerPad}},`);
  }

  // buildPayload function
  if (event.params.length > 0) {
    const interfaceName = event.interfaceName;
    lines.push(`${innerPad}buildPayload(params: ${interfaceName}) {`);
    lines.push(`${innerPad2}return {`);
    // Constants first
    for (const [k, v] of constEntries) {
      lines.push(`${innerPad2}  ${k}: ${renderConstantValue(v)},`);
    }
    // Spread params
    lines.push(`${innerPad2}  ...params,`);
    lines.push(`${innerPad2}};`);
    lines.push(`${innerPad}},`);
    lines.push(`${pad}} satisfies TrackingEvent<${interfaceName}>,`);
  } else {
    lines.push(`${innerPad}buildPayload() {`);
    if (constEntries.length === 0) {
      lines.push(`${innerPad2}return {};`);
    } else {
      lines.push(`${innerPad2}return {`);
      for (const [k, v] of constEntries) {
        lines.push(`${innerPad2}  ${k}: ${renderConstantValue(v)},`);
      }
      lines.push(`${innerPad2}};`);
    }
    lines.push(`${innerPad}},`);
    lines.push(`${pad}} satisfies TrackingEvent<void>,`);
  }

  return lines.join("\n");
}

function renderEventsObject(events: MappedEvent[], standalone: boolean): string {
  // Group by area
  const groups = new Map<string, MappedEvent[]>();
  for (const event of events) {
    const list = groups.get(event.area) ?? [];
    list.push(event);
    groups.set(event.area, list);
  }

  // Sort areas alphabetically
  const sortedAreas = [...groups.keys()].sort();

  if (sortedAreas.length === 0) {
    return "export const events = {} as const;";
  }

  const areaBlocks = sortedAreas.map((area) => {
    const areaEvents = groups.get(area)!;
    // Sort events within area alphabetically by eventName
    areaEvents.sort((a, b) => a.eventName.localeCompare(b.eventName));

    const entries = areaEvents.map((e) => renderEventEntry(e, 4, standalone)).join("\n");
    return `  ${area}: {\n${entries}\n  },`;
  });

  return `export const events = {\n${areaBlocks.join("\n")}\n} as const;`;
}

export function buildTypescript(events: MappedEvent[], options: BuildOptions): string {
  const sections: string[] = [];
  const standalone = options.standalone ?? false;

  // 1. Header (includes import for SDK mode)
  sections.push(renderHeader(events.length, options));

  // 2. Enum const objects (deduplicated by PascalCase name)
  const renderedEnums = new Set<string>();
  for (const event of events) {
    for (const field of event.params) {
      const key = enumName(field.name);
      if (field.enumValues?.length && !renderedEnums.has(key)) {
        const allBools = field.enumValues.every((v) => typeof v === "boolean");
        if (allBools && field.enumValues.includes(true) && field.enumValues.includes(false))
          continue;
        sections.push(renderEnumConst(field.name, field.enumValues));
        renderedEnums.add(key);
      }
      if (field.isArray && field.arrayItemEnum?.length && !renderedEnums.has(key)) {
        const allBools = field.arrayItemEnum.every((v) => typeof v === "boolean");
        if (allBools && field.arrayItemEnum.includes(true) && field.arrayItemEnum.includes(false))
          continue;
        sections.push(renderEnumConst(field.name, field.arrayItemEnum));
        renderedEnums.add(key);
      }
    }
  }

  // 3. Interfaces (only for events with params)
  const interfaces = events.filter((e) => e.params.length > 0).map(renderInterface);
  if (interfaces.length) sections.push(interfaces.join("\n\n"));

  // 4. Helper type + function (only in standalone mode)
  if (standalone) {
    sections.push(STANDALONE_HELPER_CODE);
  }

  // 5. Events object
  sections.push(renderEventsObject(events, standalone));

  // 6. Type exports
  sections.push(TYPE_EXPORTS);

  return `${sections.join("\n\n")}\n`;
}
