import { describe, expect, it } from "vitest";
import type { OpenTPConfig, ResolvedEvent } from "../../types";
import type { GeneratorContext, GeneratorOptions } from "../types";
import { tsSdkGenerator } from "./index";

// -- Shared Fixtures --

const baseConfig: OpenTPConfig = {
  opentp: "2026-01",
  info: { title: "My App", version: "2.0.0" },
  spec: {
    paths: { events: { root: "/events", template: "{area}/{event}.yaml" } },
    events: {
      taxonomy: {},
      payload: {
        targets: { all: ["web", "ios", "android"], mobile: ["ios", "android"] },
        schema: {
          event_name: { type: "string", required: true },
          event_category: { type: "string", required: true },
        },
      },
    },
  },
};

const emptyDict = new Map<string, (string | number | boolean)[]>();

function makeEvent(overrides: Partial<ResolvedEvent>): ResolvedEvent {
  return {
    filePath: "/events/test/event.yaml",
    relativePath: "test/event.yaml",
    key: "test::event",
    expectedKey: null,
    taxonomy: { area: "test", event: "event" },
    ignore: [],
    payload: { schema: {} },
    ...overrides,
  };
}

function makeContext(
  events: ResolvedEvent[],
  options: GeneratorOptions = {},
  dictionaries = emptyDict,
): GeneratorContext {
  return { config: baseConfig, events, dictionaries, options };
}

// -- Tests --

describe("ts-sdk generator (integration)", () => {
  it("generates complete TypeScript with all sections", () => {
    const context = makeContext([
      makeEvent({
        key: "auth::login_button_click",
        lifecycle: { status: "active" },
        payload: {
          schema: {
            event_name: { value: "login_button_click" },
            event_category: { value: "auth" },
            auth_method: {
              type: "string",
              enum: ["email", "google"],
              required: true,
            },
          },
        },
      }),
      makeEvent({
        key: "nav::page_view",
        lifecycle: { status: "active" },
        payload: {
          schema: {
            event_name: { value: "page_view" },
            event_category: { value: "nav" },
          },
        },
      }),
    ]);

    const result = tsSdkGenerator.generate(context);
    const output = result.stdout!;

    // Header
    expect(output).toContain("Auto-generated by OpenTrackPlan CLI");
    expect(output).toContain("My App v2.0.0");
    expect(output).toContain("Target: web");
    expect(output).toContain("Events: 2");
    expect(output).toContain("Compatible with @opentp/sdk createTracker()");

    // SDK import (default mode)
    expect(output).toContain("import type { TrackingEvent } from '@opentp/sdk'");

    // Enum const objects
    expect(output).toContain("export const AuthMethod = {");

    // Interface for event with params
    expect(output).toContain("export interface AuthLoginButtonClickParams");
    expect(output).toContain("auth_method: AuthMethod");

    // No interface for constants-only event
    expect(output).not.toContain("export interface NavPageViewParams");

    // Should NOT have inline helper code in SDK mode
    expect(output).not.toContain("function defineEvent");

    // Events object with new SDK-compatible format
    expect(output).toContain("export const events = {");
    expect(output).toContain("loginButtonClick: {");
    expect(output).toContain("key: 'auth::login_button_click'");
    expect(output).toContain("buildPayload(params: AuthLoginButtonClickParams)");
    expect(output).toContain("satisfies TrackingEvent<AuthLoginButtonClickParams>");
    expect(output).toContain("pageView: {");
    expect(output).toContain("key: 'nav::page_view'");
    expect(output).toContain("satisfies TrackingEvent<void>");

    // Constants
    expect(output).toContain("event_name: 'login_button_click'");
    expect(output).toContain("event_category: 'auth'");
    expect(output).toContain("event_name: 'page_view'");
    expect(output).toContain("event_category: 'nav'");

    // Type exports
    expect(output).toContain("export type EventsMap");
    expect(output).toContain("export type AreaName");
    expect(output).toContain("export type EventName");

    // Area ordering (auth before nav)
    expect(output.indexOf("auth:")).toBeLessThan(output.indexOf("nav:"));

    // stdout mode — no files
    expect(result.files).toBeUndefined();
  });

  it("filters out deprecated events", () => {
    const context = makeContext([
      makeEvent({
        key: "auth::login",
        lifecycle: { status: "active" },
        payload: {
          schema: {
            event_name: { value: "login" },
            event_category: { value: "auth" },
          },
        },
      }),
      makeEvent({
        key: "old::removed_event",
        lifecycle: { status: "deprecated" },
        payload: {
          schema: {
            event_name: { value: "removed" },
            event_category: { value: "old" },
          },
        },
      }),
    ]);

    const result = tsSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("login");
    expect(output).not.toContain("removedEvent");
    expect(output).not.toContain("OldRemovedEvent");
    expect(output).not.toContain("old::removed_event");
    expect(output).toContain("Events: 1");
  });

  it("respects --target option", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "auth::login",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "login" },
              event_category: { value: "auth" },
            },
          },
        }),
      ],
      { target: "ios" },
    );

    const result = tsSdkGenerator.generate(context);
    expect(result.stdout).toContain("Target: ios");
    expect(result.stdout).toContain("login");
  });

  it("excludes events not available for the requested target", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "onboarding::step_complete",
          payload: {
            mobile: {
              schema: {
                event_name: { value: "step_complete" },
                event_category: { value: "onboarding" },
                step: { type: "number", required: true },
              },
            },
          },
        }),
      ],
      { target: "web" },
    );

    const result = tsSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).not.toContain("stepComplete");
    expect(output).toContain("Events: 0");
    expect(output).toContain("export const events = {} as const;");
  });

  it("returns files array when --output is specified", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "auth::login",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "login" },
              event_category: { value: "auth" },
            },
          },
        }),
      ],
      { output: "dist/tracker.ts" },
    );

    const result = tsSdkGenerator.generate(context);

    expect(result.files).toHaveLength(1);
    expect(result.files![0].path).toBe("dist/tracker.ts");
    expect(result.files![0].content).toContain("Auto-generated by OpenTrackPlan CLI");
    expect(result.files![0].content).toContain("export const events = {");
    expect(result.stdout).toBeUndefined();
  });

  it("handles versioned payload with $ref inheritance", () => {
    const context = makeContext([
      makeEvent({
        key: "auth::login_click",
        lifecycle: { status: "active" },
        payload: {
          all: {
            current: "stable",
            stable: "1.1.0",
            "1.0.0": {
              schema: {
                event_name: { value: "login_click" },
                event_category: { value: "auth" },
                auth_method: {
                  type: "string",
                  enum: ["email", "google"],
                  required: true,
                },
              },
            },
            "1.1.0": {
              $ref: "1.0.0",
              schema: {
                screen_name: { type: "string", required: false },
              },
            },
          },
        },
      }),
    ]);

    const result = tsSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("export const AuthMethod = {");
    expect(output).toContain("export interface AuthLoginClickParams");
    // Inherited from 1.0.0
    expect(output).toContain("auth_method: AuthMethod");
    // Added in 1.1.0
    expect(output).toContain("screen_name?: string");
    // Constants
    expect(output).toContain("event_name: 'login_click'");
    expect(output).toContain("event_category: 'auth'");
  });

  it("throws when no target can be determined", () => {
    const noTargetConfig: OpenTPConfig = {
      ...baseConfig,
      spec: {
        ...baseConfig.spec,
        events: {
          ...baseConfig.spec.events,
          payload: {
            targets: { all: [] },
            schema: baseConfig.spec.events.payload.schema,
          },
        },
      },
    };

    const context: GeneratorContext = {
      config: noTargetConfig,
      events: [
        makeEvent({
          key: "auth::login",
          payload: { schema: { event_name: { value: "login" } } },
        }),
      ],
      dictionaries: emptyDict,
      options: {},
    };

    expect(() => tsSdkGenerator.generate(context)).toThrow("ts-sdk generator requires a target");
  });

  it("resolves dictionary values into union types", () => {
    const dicts = new Map<string, (string | number | boolean)[]>([
      ["auth_methods", ["email", "google", "sso"]],
    ]);

    const context = makeContext(
      [
        makeEvent({
          key: "auth::signup",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "signup" },
              event_category: { value: "auth" },
              method: { type: "string", dict: "auth_methods", required: true },
            },
          },
        }),
      ],
      {},
      dicts,
    );

    const result = tsSdkGenerator.generate(context);
    const output = result.stdout!;

    expect(output).toContain("export const Method = {");
    expect(output).toContain("method: Method");
  });

  it("generates standalone format when standalone option is true", () => {
    const context = makeContext(
      [
        makeEvent({
          key: "auth::login",
          lifecycle: { status: "active" },
          payload: {
            schema: {
              event_name: { value: "login" },
              event_category: { value: "auth" },
              auth_method: {
                type: "string",
                enum: ["email", "google"],
                required: true,
              },
            },
          },
        }),
      ],
      { standalone: true },
    );

    const result = tsSdkGenerator.generate(context);
    const output = result.stdout!;

    // Should NOT import from @opentp/sdk
    expect(output).not.toContain("@opentp/sdk");
    expect(output).not.toContain("Compatible with @opentp/sdk createTracker()");

    // Should have inline helper code
    expect(output).toContain("export interface TrackingEvent<TParams = void>");
    expect(output).toContain("function defineEvent");

    // Should use defineEvent helper
    expect(output).toContain("login: defineEvent<AuthLoginParams>(");

    // Should NOT use satisfies
    expect(output).not.toContain("satisfies");
  });

  it("groups multiple events in the same area correctly", () => {
    const context = makeContext([
      makeEvent({
        key: "auth::login",
        lifecycle: { status: "active" },
        payload: {
          schema: {
            event_name: { value: "login" },
            event_category: { value: "auth" },
            method: { type: "string", required: true },
          },
        },
      }),
      makeEvent({
        key: "auth::signup",
        lifecycle: { status: "active" },
        payload: {
          schema: {
            event_name: { value: "signup" },
            event_category: { value: "auth" },
            referral: { type: "string", required: false },
          },
        },
      }),
      makeEvent({
        key: "nav::page_view",
        lifecycle: { status: "active" },
        payload: {
          schema: {
            event_name: { value: "page_view" },
            event_category: { value: "nav" },
          },
        },
      }),
    ]);

    const result = tsSdkGenerator.generate(context);
    const output = result.stdout!;

    // Both auth events grouped under same area key
    expect(output).toContain("auth: {");
    expect(output).toContain("nav: {");

    // Both login and signup appear between "auth: {" and "nav: {"
    const authStart = output.indexOf("auth: {");
    const navStart = output.indexOf("nav: {");
    const authSection = output.slice(authStart, navStart);
    expect(authSection).toContain("login:");
    expect(authSection).toContain("signup:");

    // Alphabetical within area: login before signup
    expect(authSection.indexOf("login:")).toBeLessThan(authSection.indexOf("signup:"));

    // Nav in separate block
    expect(output).toContain("nav: {");
    expect(output).toContain("pageView:");

    expect(output).toContain("Events: 3");
  });
});
